#!/usr/bin/env bash
# configure web-02 to be identical to web-01
FILE="/etc/nginx/sites-available/default"
ERRORFI="/usr/share/nginx/html/404error.html"

REDIR="\n\tlocation /redirect_me {\n\t\treturn 301 https://youtu.be/dQw4w9WgXcQ;\n\t}\n"
ERRORREDIR="\n\terror_page 404 /404error.html;\n\tlocation = /404error.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}\n"
CUSTOMHEAD='\n\tadd_header X-Served-By $hostname;\n'

STRING="Hello World!"
FOUR="Ceci n'est pas une page"

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "$STRING" > /var/www/html/index.nginx-debian.html
sed -i "37i\ $REDIR" "$FILE"

echo "$FOUR" > "$ERRORFI"
sed -i "37i\ $ERRORREDIR" "$FILE"

sed -i "37i\ $CUSTOMHEAD" "$FILE"
service nginx restart
