#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the requirements

cp /etc/hosts ~/hosts.new
sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
